-- mig-001
-- CRIAÇÃO DA TABELA AREA

CREATE TABLE portaldamerenda.area (
	ID_AREA INT AUTO_INCREMENT,
	INTERIOR INT,
	DESCRICAO VARCHAR(200),
	CONSTRAINT area_PK PRIMARY KEY (ID_AREA)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;

