/*
CREATED		22/09/2013
MODIFIED		28/09/2013
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/


DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS TIPO_CONTATO;
DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS ESCOLA;
DROP TABLE IF EXISTS INSTITUICAO;
DROP TABLE IF EXISTS SISTEMA;
DROP TABLE IF EXISTS AREA;
DROP TABLE IF EXISTS USERS_RESOURCES;
DROP TABLE IF EXISTS RESOURCES;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS USERS;


CREATE TABLE USERS (
	PERSON_ID INT NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD CHAR(100) NOT NULL,
	STATUS INT NOT NULL,
	UNIQUE (USERNAME),
 PRIMARY KEY (PERSON_ID)) ENGINE = INNODB;

CREATE TABLE PERSON (
	ID_PERSON INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
 PRIMARY KEY (ID_PERSON)) ENGINE = INNODB;

CREATE TABLE RESOURCES (
	ID_RESOURCE INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(200),
	NAME VARCHAR(200) NOT NULL,
	STATUS INT NOT NULL,
	UNIQUE (NAME),
 PRIMARY KEY (ID_RESOURCE)) ENGINE = INNODB;

CREATE TABLE USERS_RESOURCES (
	RESOURCE_ID INT NOT NULL,
	PERSON_ID INT NOT NULL,
 PRIMARY KEY (RESOURCE_ID,PERSON_ID)) ENGINE = INNODB;

CREATE TABLE AREA (
	ID_AREA INT NOT NULL AUTO_INCREMENT,
	INTERIOR INT NOT NULL COMMENT '0 - NAO
1 - SIM',
	DESCRICAO VARCHAR(200) NOT NULL,
	SISTEMA_ID INT,
 PRIMARY KEY (ID_AREA)) ENGINE = INNODB;

CREATE TABLE SISTEMA (
	ID_SISTEMA INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(40) NOT NULL,
 PRIMARY KEY (ID_SISTEMA)) ENGINE = INNODB;

CREATE TABLE INSTITUICAO (
	ID_INSTITUICAO INT NOT NULL AUTO_INCREMENT,
	SISTEMA_ID INT NOT NULL,
	RAZAO_SOCIAL VARCHAR(200),
	NOME_FANTASIA VARCHAR(200),
	CNPJ VARCHAR(14),
	INSCRICAO_ESTADUAL VARCHAR(100) AUTO_INCREMENT,
	IND_STATUS_REGISTRO INT NOT NULL DEFAULT 1,
	UNIQUE (RAZAO_SOCIAL),
	UNIQUE (INSCRICAO_ESTADUAL),
 PRIMARY KEY (ID_INSTITUICAO)) ENGINE = INNODB;

CREATE TABLE ESCOLA (
	INSTITUICAO_ID INT NOT NULL,
	AREA_ID INT NOT NULL,
	REFERENCIA_SE VARCHAR(100),
	QTD_ALUNOS INT,
	ITEM VARCHAR(20),
	INTERIOR INT DEFAULT 0,
	OBS VARCHAR(255),
 PRIMARY KEY (INSTITUICAO_ID)) ENGINE = INNODB;

CREATE TABLE ENDERECO (
	INSTITUICAO_ID INT NOT NULL,
	CIDADE_ID INT NOT NULL,
	RUA VARCHAR(300),
	BAIRRO VARCHAR(300),
	NUMERO VARCHAR(20),
 PRIMARY KEY (INSTITUICAO_ID)) ENGINE = INNODB;

CREATE TABLE ESTADO (
	ID_ESTADO INT NOT NULL AUTO_INCREMENT,
	UF CHAR(2),
	NOME VARCHAR(100),
	UNIQUE (UF),
 PRIMARY KEY (ID_ESTADO)) ENGINE = INNODB;

CREATE TABLE CIDADE (
	ID_CIDADE INT NOT NULL AUTO_INCREMENT,
	ESTADO_ID INT NOT NULL,
	NOME VARCHAR(300),
 PRIMARY KEY (ID_CIDADE)) ENGINE = INNODB;

CREATE TABLE CONTATO (
	ID_CONTATO INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	TIPO_CONTATO_ID INT NOT NULL,
	INSTITUICAO_ID INT NOT NULL,
 PRIMARY KEY (ID_CONTATO,TIPO_CONTATO_ID,INSTITUICAO_ID)) ENGINE = INNODB;

CREATE TABLE TIPO_CONTATO (
	ID_TIPO_CONTATO INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
 PRIMARY KEY (ID_TIPO_CONTATO)) ENGINE = INNODB;

CREATE TABLE FORNECEDOR (
	NOME_RESPONSAVEL VARCHAR(200),
	DOCUMENTO_RESPONSAVEL VARCHAR(100),
	TIPO_DOCUMENTO_ID INT NOT NULL,
	INSTITUICAO_ID INT NOT NULL,
 PRIMARY KEY (TIPO_DOCUMENTO_ID,INSTITUICAO_ID)) ENGINE = INNODB;

CREATE TABLE TIPO_DOCUMENTO (
	ID_TIPO_DOCUMENTO INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
 PRIMARY KEY (ID_TIPO_DOCUMENTO)) ENGINE = INNODB;


ALTER TABLE USERS_RESOURCES ADD FOREIGN KEY (PERSON_ID) REFERENCES USERS (PERSON_ID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE USERS ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID_PERSON) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE USERS_RESOURCES ADD FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCES (ID_RESOURCE) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ESCOLA ADD FOREIGN KEY (AREA_ID) REFERENCES AREA (ID_AREA) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE AREA ADD FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMA (ID_SISTEMA) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE INSTITUICAO ADD FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMA (ID_SISTEMA) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ESCOLA ADD FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID_INSTITUICAO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ENDERECO ADD FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID_INSTITUICAO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE CONTATO ADD FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID_INSTITUICAO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE FORNECEDOR ADD FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID_INSTITUICAO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE CIDADE ADD FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID_ESTADO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ENDERECO ADD FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID_CIDADE) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE CONTATO ADD FOREIGN KEY (TIPO_CONTATO_ID) REFERENCES TIPO_CONTATO (ID_TIPO_CONTATO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE FORNECEDOR ADD FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;


/* USERS PERMISSIONS */


