/*
CREATED		22/09/2013
MODIFIED		22/09/2013
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/


DROP TABLE IF EXISTS USERS_RESOURCES;
DROP TABLE IF EXISTS RESOURCES;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS USERS;


CREATE TABLE USERS (
	PERSON_ID INT NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD CHAR(100) NOT NULL,
	STATUS INT NOT NULL,
	UNIQUE (USERNAME),
 PRIMARY KEY (PERSON_ID)) ENGINE = MYISAM;

CREATE TABLE PERSON (
	ID_PERSON INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
 PRIMARY KEY (ID_PERSON)) ENGINE = MYISAM;

CREATE TABLE RESOURCES (
	ID_RESOURCE INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(200),
	NAME VARCHAR(200) NOT NULL,
	STATUS INT NOT NULL,
	UNIQUE (NAME),
 PRIMARY KEY (ID_RESOURCE)) ENGINE = MYISAM;

CREATE TABLE USERS_RESOURCES (
	RESOURCE_ID INT NOT NULL,
	PERSON_ID INT NOT NULL,
 PRIMARY KEY (RESOURCE_ID,PERSON_ID)) ENGINE = MYISAM;


ALTER TABLE USERS_RESOURCES ADD FOREIGN KEY (PERSON_ID) REFERENCES USERS (PERSON_ID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE USERS ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID_PERSON) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE USERS_RESOURCES ADD FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCES (ID_RESOURCE) ON DELETE  RESTRICT ON UPDATE  RESTRICT;


/* USERS PERMISSIONS */


